{{- if .Values.nodePlugin.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "gitrepo-csi-driver.fullname" . }}-nodeplugin
  labels:
    app.kubernetes.io/name: {{ include "gitrepo-csi-driver.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: nodeplugin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gitrepo-csi-driver.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: nodeplugin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gitrepo-csi-driver.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: nodeplugin
{{- with .Values.nodePlugin.podLabels }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: {{ include "gitrepo-csi-driver.serviceAccountName" . }}
{{- with .Values.nodePlugin.podSecurityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
{{- end }}
{{- if .Values.nodePlugin.permissions.enabled }}
      initContainers:
        - name: prepare-nodeplugin-dirs
          image: {{ .Values.nodePlugin.image.repository }}:{{ .Values.nodePlugin.image.tag }}
          imagePullPolicy: {{ .Values.nodePlugin.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - chmod 0775 /var/lib/gitcontent/cache && chown -R {{ .Values.nodePlugin.git.runAsUser }}:{{ .Values.nodePlugin.git.runAsGroup }} /var/lib/gitcontent/cache
          securityContext:
            runAsUser: {{ .Values.nodePlugin.permissions.runAsUser }}
            runAsGroup: {{ .Values.nodePlugin.permissions.runAsGroup }}
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - CHOWN
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: cache
              mountPath: /var/lib/gitcontent/cache
          resources:
{{ toYaml .Values.nodePlugin.permissions.resources | indent 12 }}
{{- end }}
      containers:
        - name: node-driver-registrar
          image: {{ .Values.nodePlugin.registrar.image.repository }}:{{ .Values.nodePlugin.registrar.image.tag }}
          imagePullPolicy: {{ .Values.nodePlugin.registrar.image.pullPolicy }}
          args:
            - --csi-address=/csi/csi.sock
            - --kubelet-registration-path={{ .Values.nodePlugin.pluginDir }}/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
          resources:
{{ toYaml .Values.nodePlugin.registrar.resources | indent 12 }}
        - name: nodeplugin
          image: {{ .Values.nodePlugin.image.repository }}:{{ .Values.nodePlugin.image.tag }}
          imagePullPolicy: {{ .Values.nodePlugin.image.pullPolicy }}
{{- with .Values.nodePlugin.securityContext }}
          securityContext:
{{ toYaml . | indent 12 }}
{{- end }}
          env:
            - name: GITCONTENT_POLICY_FILE
              value: {{ .Values.nodePlugin.env.policyFile | quote }}
            - name: GITCONTENT_CACHE_DIR
              value: {{ .Values.nodePlugin.env.cacheDir | quote }}
            - name: GITCONTENT_ADDR
              value: {{ .Values.nodePlugin.env.listenAddr | quote }}
            - name: CSI_ENDPOINT
              value: {{ .Values.nodePlugin.env.csiEndpoint | quote }}
{{- if .Values.nodePlugin.git.dropPrivileges }}
            - name: GITCONTENT_GIT_RUN_AS_UID
              value: {{ .Values.nodePlugin.git.runAsUser | quote }}
            - name: GITCONTENT_GIT_RUN_AS_GID
              value: {{ .Values.nodePlugin.git.runAsGroup | quote }}
{{- end }}
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - name: metrics
              containerPort: 8080
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: policy
              mountPath: /etc/gitcontent
            - name: cache
              mountPath: /var/lib/gitcontent/cache
            - name: kubelet-pods
              mountPath: {{ printf "%s/pods" .Values.nodePlugin.kubeletRootDir }}
          resources:
{{ toYaml .Values.nodePlugin.resources | indent 12 }}
      volumes:
        - name: socket-dir
          hostPath:
            path: {{ .Values.nodePlugin.pluginDir }}
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: {{ .Values.nodePlugin.registrationDir }}
            type: DirectoryOrCreate
        - name: policy
          configMap:
            name: {{ default (printf "%s-policy" (include "gitrepo-csi-driver.fullname" .)) .Values.policy.existingConfigMap }}
        - name: cache
          hostPath:
            path: /var/lib/gitrepo-csi-driver/cache
            type: DirectoryOrCreate
        - name: kubelet-pods
          hostPath:
            path: {{ printf "%s/pods" .Values.nodePlugin.kubeletRootDir }}
            type: DirectoryOrCreate
      tolerations:
{{ toYaml .Values.nodePlugin.tolerations | indent 8 }}
{{- with .Values.nodePlugin.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.nodePlugin.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
{{- end }}
{{- end }}
