{{- if .Values.admissionWebhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitrepo-csi-driver.fullname" . }}-admission
  labels:
    app.kubernetes.io/name: {{ include "gitrepo-csi-driver.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: admission
spec:
  type: {{ .Values.admissionWebhook.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "gitrepo-csi-driver.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: admission
  ports:
    - name: http
      port: {{ .Values.admissionWebhook.service.port }}
      targetPort: http
{{- end }}
