name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Download dependencies
        run: go mod download

      - parallel:
        - name: Lint
          uses: golangci/golangci-lint-action@v9
          with:
            version: latest
            args: --config .golangci-lint.yml

        - name: Run go vet
          run: go vet ./...

        - name: Unit tests
          run: go test ./...

        - name: Run GoReleaser check
          uses: goreleaser/goreleaser-action@v7
          with:
            version: latest
            args: check

        - name: Run Gosec Security Scanner
          uses: securego/gosec@v2.28.0
          with:
            # we let the report trigger content trigger a failure using the GitHub Security features.
            args: '-no-fail -fmt sarif -out gosec_results.sarif ./...'

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: gosec_results.sarif



  helm-lint:
    name: Helm Lint & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        helm-version: [v4.2.4]
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Helm
        uses: azure/setup-helm@v5
        with:
          version: ${{ matrix.helm-version }}

      - name: Helm lint
        run: helm lint helm/gitrepo-csi-driver

      - name: Helm render check
        run: helm template gitrepo-csi-driver helm/gitrepo-csi-driver > /tmp/rendered.yaml

      - name: Unit tests
        uses: d3adb5/helm-unittest-action@v2
        with:
          install-mode: "if-not-present"
          helm-version: ${{ matrix.helm-version }}
          unittest-version: v1.1.2
          github-token: ${{ secrets.GITHUB_TOKEN }}
